[package]
name = "db-api"
version = "0.1.0"
edition = "2021"

[dependencies]
db-core = { path = "../db-core" }
db-types = { path = "../db-types" }
db-runtime = { path = "../db-runtime" }
axum = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }