[package]
name = "in-mem-db-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Tick-based runtime and procedure execution system"
repository.workspace = true
readme.workspace = true

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
in-mem-db-core = { path = "../in-mem-db-core", version = "0.1.0" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }

rayon = { workspace = true, optional = true }
hex = "0.4.3"
parking_lot = "0.12.5"

[dev-dependencies]
ntest = "0.9.5"
